MODULE set_precisions
IMPLICIT NONE
!PRIVATE
INTEGER, PARAMETER :: SGL = SELECTED_REAL_KIND(p=6, r=37)
!integer, parameter :: DBL = SELECTED_REAL_KIND(p=6, r=37)
INTEGER, PARAMETER :: DBL = SELECTED_REAL_KIND(p=15, r=307)
INTEGER, PARAMETER :: QPL = SELECTED_REAL_KIND(p=33, r=4931)
END MODULE set_precisions
